# Generated by Django 4.2 on 2023-05-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
