# Generated by Django 4.2 on 2023-05-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='products',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='product_name',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpayment',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpayment',
            name='seller_name',
            field=models.CharField(default=213, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='checkout_id',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Purchased',
        ),
    ]
