# Generated by Django 4.2 on 2023-05-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment'),
        ('payment', '0004_remove_userpayment_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='checkout_id',
            field=models.CharField(max_length=500),
        ),
    ]
