# Generated by Django 4.2 on 2023-06-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_featurevector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
