# Generated by Django 4.2 on 2023-06-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_feature_vector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureVector',
        ),
    ]
