# Generated by Django 4.2 on 2023-06-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_featurevector'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('feature_vector', models.TextField()),
            ],
        ),
    ]
